version: '3.10'
services:
  backend:
    container_name: DataGeneration
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:5000"
    environment:
      - ALLOWED_ORIGIN=${FRONTEND_URL}
    volumes:
      - ./backend:/app
  frontend:
    container_name: vue-js
    build: 
      context: ./vue-frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - ALLOWED_ORIGIN=${FRONTEND_URL}
    volumes:
      - ./vue-frontend:/app