version: '3.10'
services:
  backend:
    container_name: DataGeneration
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:5000"
    environment:
      - ALLOWED_ORIGIN=${FRONTEND_URL:-http://localhost}
    volumes:
      - ./backend:/app
  app:
    container_name: vue-js
    build: 
      context: ./vue-frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    environment:
      -  API_URL=${API_URL:-http://localhost:8080}
    volumes:
      - ./vue-frontend:/project
      - /project/node_modules